### ISSUE TITLE
[minor] Declared torchmetrics floor (>=0.6.0) is unsatisfiable: Multiclass* metrics imported in utils.py only exist …

### ISSUE THREAD

**Issue by martinez-hub** [mit-ll-responsible-ai/equine#205]
**Severity:** minor  
**Location:** `src/equine/utils.py:12`  
**Found by review lenses:** deprecation-portability

### What is wrong

pyproject.toml:23 declares `torchmetrics >= 0.6.0`, but utils.py:12-17 imports MulticlassAccuracy, MulticlassCalibrationError, MulticlassConfusionMatrix and MulticlassF1Score from torchmetrics.classification. These classes were introduced in the torchmetrics 0.10 classification rewrite. Reproduced: with torchmetrics==0.9.3 installed, `import equine` fails at utils.py:12 with `ImportError: cannot import name 'MulticlassAccuracy' from 'torchmetrics.classification'`. Any resolver that keeps an existing torchmetrics 0.6-0.9 install (or a downstream pin) yields an uninstallable-in-practice package.

### Suggested fix

Change pyproject.toml to `torchmetrics >= 0.10.0`.

### Verification

An independent, refutation-biased pass re-read the code (and ran it where noted) and could not disprove the finding:

> Could not refute; the defect is real and reproduced.
> 
> Checked: `src/equine/utils.py:12-17` imports `MulticlassAccuracy, MulticlassCalibrationError, MulticlassConfusionMatrix, MulticlassF1Score` from `torchmetrics.classification` at module import time (unconditionally, no try/except or version guard). `pyproject.toml:25` declares `"torchmetrics >= 0.6.0"` with no upper/lower refinement anywhere else: the tox `[testenv]` deps (pyproject.toml:160-172), `[testenv:coverage]`, and `[testenv:pyright]` blocks do not mention torchmetrics at all, and `grep -rn torchmetrics` across the repo finds no lock file or other constraint. `git log -S` shows the `>= 0.6.0` floor dates from commit c53246a (2023-07-05) while the Multiclass* imports were introduced in 4761267 "Feature/typesafing (#91)" (2025-01-08) without bumping the floor.
> 
> Reproduction in a scratch venv (python 3.10, torch>=2.0): with `torchmetrics==0.9.3` installed, `from torchmetrics.classification import MulticlassAccuracy` raises `ImportError: cannot import name 'MulticlassAccuracy' from 'torchmetrics.classification'`; with `torchmetrics==0.10.0` all four imports succeed. So the true minimum is 0.10.0, and `import equine` (which imports utils via `__init__`) fails on any torchmetrics in [0.6.0, 0.10.0).
> 
> Severity downgraded from "important" to "minor": a fresh `pip install equine` resolves the newest torchmetrics and works; the failure only bites environments that already hold (or downstream-pin) torchmetrics 0.6-0.9, e.g. older Lightning stacks, where the resolver wrongly accepts the existing install and the package then fails at import. It is a real, one-line packaging-metadata bug, not a runtime/security defect. Fix: change pyproject.toml:25 to `"torchmetrics >= 0.10.0"`.

---
_Found by an automated adversarial code review of `main` at 74a0cb5 (2026-09-18): ten independent reviewer agents, deduplication, then a skeptic agent per finding that tried to refute it by reading and running the code. Filed by @martinez-hub. Finding #41 of 72 confirmed._
